# Generated by Django 6.0.7 on 2026-10-08 12:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('workspace_invitation', 'Workspace invitation'), ('owner_invitation', 'Owner invitation'), ('installation_admin_invitation', 'Installation administrator invitation'), ('password_reset', 'Password reset'), ('automation_run', 'Automation run')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('encrypted_data', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'available_at'], name='delivery_ou_status_a89a92_idx')],
            },
        ),
    ]
