# Generated by Django 6.0.7 on 2026-10-05 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyactivity_company_archived_at_and_more'),
        ('contacts', '0001_initial'),
        ('organizations', '0018_organizationsettings_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('archived', 'Archived'), ('restored', 'Restored')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('first_name', 'last_name', 'id')},
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('former', 'Former')], default='active', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('is_primary', True)), fields=('company',), name='unique_active_primary_contact_per_company'),
        ),
        migrations.AddField(
            model_name='contactactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactactivity',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contactactivity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_activities', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='contactactivity',
            index=models.Index(fields=['contact', 'created_at'], name='contacts_co_contact_205821_idx'),
        ),
    ]
