# Generated by Django 6.0.7 on 2026-10-06 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_companyactivity_company_archived_at_and_more'),
        ('contacts', '0002_contactactivity_alter_contact_options_and_more'),
        ('deals', '0002_alter_deal_options_deal_amount_includes_tax_and_more'),
        ('organizations', '0018_organizationsettings_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('task', 'Task'), ('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting')], default='task', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('due_at', models.DateTimeField()),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crm_tasks', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='companies.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_crm_tasks', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_tasks', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='deals.deal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organizations.organization')),
            ],
            options={
                'ordering': ('completed_at', 'due_at', '-priority', 'created_at'),
                'indexes': [models.Index(fields=['organization', 'completed_at', 'due_at'], name='task_org_open_due_idx'), models.Index(fields=['organization', 'assigned_to', 'due_at'], name='task_org_owner_due_idx'), models.Index(fields=['organization', 'deal'], name='task_org_deal_idx')],
            },
        ),
    ]
