# Generated by Django 6.0.7 on 2026-10-06 09:27

from django.db import migrations, models


def mark_existing_completed_tasks(apps, schema_editor):
    task_model = apps.get_model("activities", "Task")
    task_model.objects.filter(completed_at__isnull=False).update(
        workflow_status="completed"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workflow_status',
            field=models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('completed', 'Completed')], default='todo', max_length=20),
        ),
        migrations.RunPython(
            mark_existing_completed_tasks, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        workflow_status="completed", completed_at__isnull=False
                    )
                    | models.Q(
                        ~models.Q(workflow_status="completed"),
                        completed_at__isnull=True,
                    )
                ),
                name="task_completion_matches_workflow",
            ),
        ),
    ]
