# Generated by Django 6.0.7 on 2026-10-05 19:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_companyactivity_company_archived_at_and_more'),
        ('deals', '0002_alter_deal_options_deal_amount_includes_tax_and_more'),
        ('organizations', '0018_organizationsettings_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=24, max_digits=5)),
                ('billing_interval', models.CharField(choices=[('one_off', 'One-off'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Every six months'), ('annual', 'Annual')], max_length=20)),
                ('start_date', models.DateField()),
                ('next_billing_date', models.DateField()),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('operational_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='companies.company')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_subscriptions', to='organizations.organization')),
                ('originating_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='deals.deal')),
            ],
            options={
                'ordering': ('next_billing_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_start', models.DateField()),
                ('coverage_end', models.DateField()),
                ('due_date', models.DateField()),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('state', models.CharField(choices=[('open', 'Open'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='organizations.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='subscriptions.customersubscription')),
            ],
            options={
                'ordering': ('due_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.charge')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-paid_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('internal_code', models.CharField(blank=True, max_length=50)),
                ('default_net_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=24, max_digits=5)),
                ('billing_interval', models.CharField(choices=[('one_off', 'One-off'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Every six months'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_catalog_items', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.servicecatalogitem'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('subscription', 'due_date'), name='unique_charge_due_date_per_subscription'),
        ),
        migrations.AddConstraint(
            model_name='servicecatalogitem',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_code', ''), _negated=True), fields=('organization', 'internal_code'), name='unique_service_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='servicecatalogitem',
            constraint=models.CheckConstraint(condition=models.Q(('default_tax_rate__gte', 0), ('default_tax_rate__lte', 100)), name='catalog_tax_rate_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='customersubscription',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='subscription_tax_rate_between_0_and_100'),
        ),
    ]
