# Generated by Django 6.0.7 on 2026-10-05 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyactivity_company_archived_at_and_more'),
        ('deals', '0002_alter_deal_options_deal_amount_includes_tax_and_more'),
        ('organizations', '0018_organizationsettings_address_line_1_and_more'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0), ('net_amount__gte', 0), ('tax_amount__gte', 0)), name='charge_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='charge_tax_rate_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_end__gte', models.F('coverage_start'))), name='charge_coverage_dates_in_order'),
        ),
        migrations.AddConstraint(
            model_name='customersubscription',
            constraint=models.CheckConstraint(condition=models.Q(('net_price__gte', 0)), name='subscription_net_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='customersubscription',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='subscription_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='servicecatalogitem',
            constraint=models.CheckConstraint(condition=models.Q(('default_net_price__gte', 0)), name='catalog_net_price_not_negative'),
        ),
    ]
