# Generated by Django 6.0.7 on 2026-10-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_charge_charge_amounts_not_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='cancellation_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
