# Generated by Django 6.0.7 on 2026-10-05 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_customer_codes(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    organization_ids = Company.objects.order_by().values_list('organization_id', flat=True).distinct()
    for organization_id in organization_ids:
        companies = Company.objects.filter(organization_id=organization_id).order_by('created_at', 'id')
        for number, company in enumerate(companies, start=1):
            company.customer_code = f'CUS-{number:05d}'
            company.save(update_fields=('customer_code',))


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_company_address_line_1_and_more'),
        ('organizations', '0018_organizationsettings_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('contact_added', 'Contact added'), ('archived', 'Archived'), ('restored', 'Restored')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='customer_code',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.RunPython(populate_customer_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='company',
            name='customer_code',
            field=models.CharField(max_length=24),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('organization', 'customer_code'), name='unique_company_customer_code_per_organization'),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_activities', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='companyactivity',
            index=models.Index(fields=['company', 'created_at'], name='companies_c_company_87eb13_idx'),
        ),
    ]
