# Generated by Django 6.0.7 on 2026-10-05 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyactivity_company_archived_at_and_more'),
        ('contacts', '0002_contactactivity_alter_contact_options_and_more'),
        ('deals', '0001_initial'),
        ('organizations', '0018_organizationsettings_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ('stage', 'sort_order', 'created_at')},
        ),
        migrations.AddField(
            model_name='deal',
            name='amount_includes_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='deal_tax_rate_between_0_and_100'),
        ),
    ]
