# Generated by Django 6.0.7 on 2026-09-22 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    OrganizationSettings = apps.get_model("organizations", "OrganizationSettings")
    OrganizationSettings.objects.using(schema_editor.connection.alias).bulk_create(
        [
            OrganizationSettings(organization_id=organization.id)
            for organization in Organization.objects.using(schema_editor.connection.alias)
            .filter(settings__isnull=True)
            .only("id")
        ]
    )


def create_installation_state(apps, schema_editor):
    InstallationState = apps.get_model("organizations", "InstallationState")
    InstallationState.objects.using(schema_editor.connection.alias).get_or_create(pk=1)


def backfill_fallback(apps, schema_editor):
    InstallationState = apps.get_model("organizations", "InstallationState")
    EmailAccount = apps.get_model("organizations", "EmailAccount")
    state, _ = InstallationState.objects.using(schema_editor.connection.alias).get_or_create(pk=1)
    if state.fallback_email_account_id is None:
        account = (
            EmailAccount.objects.using(schema_editor.connection.alias)
            .filter(is_default=True, is_active=True)
            .order_by("created_at")
            .first()
        )
        if account:
            state.fallback_email_account_id = account.pk
            state.save(update_fields=("fallback_email_account",))

class Migration(migrations.Migration):

    replaces = [('organizations', '0001_initial'), ('organizations', '0002_organizationmembership'), ('organizations', '0003_organizationsettings_emailaccount'), ('organizations', '0004_create_default_organization_settings'), ('organizations', '0005_installationstate'), ('organizations', '0006_organizationinvitation'), ('organizations', '0007_organizationinvitation_unique_pending_invitation_per_email'), ('organizations', '0008_installationstate_fallback_email_account'), ('organizations', '0009_backfill_installation_fallback_email_account')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_membership'), models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('organization',), name='unique_owner_per_organization')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('locale', models.CharField(default='en-us', max_length=20)),
                ('default_from_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('smtp', 'SMTP')], default='smtp', max_length=30)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', models.TextField()),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_email_account_name_per_organization'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='unique_default_email_account_per_organization')],
            },
        ),
        migrations.RunPython(
            code=create_default_settings,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='InstallationState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(
            code=create_installation_state,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'email'], name='organizatio_organiz_f35a05_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True)), fields=('organization', 'email'), name='unique_pending_invitation_per_email')],
            },
        ),
        migrations.AddField(
            model_name='installationstate',
            name='fallback_email_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_fallback_for', to='organizations.emailaccount'),
        ),
        migrations.RunPython(
            code=backfill_fallback,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
