# Generated by Django 6.0.7 on 2026-09-21 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizationinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True)), fields=('organization', 'email'), name='unique_pending_invitation_per_email'),
        ),
    ]
