# Generated by Django 6.0.7 on 2026-09-21 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organizationinvitation_unique_pending_invitation_per_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationstate',
            name='fallback_email_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_fallback_for', to='organizations.emailaccount'),
        ),
    ]
