# Generated by Django 6.0.7 on 2026-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_organizationprovisioning_workspacecreatorgrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationBackupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('backup', 'Backup'), ('restore_test', 'Restore test')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('completed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-completed_at', '-id'),
                'indexes': [models.Index(fields=['kind', '-completed_at'], name='organizatio_kind_6241e2_idx')],
            },
        ),
    ]
