# Generated by Django 6.0.7 on 2026-10-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_installation_backup_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceaccessevent',
            name='action',
            field=models.CharField(choices=[('grant_creator', 'Grant workspace creator'), ('revoke_creator', 'Revoke workspace creator'), ('create_workspace', 'Create workspace'), ('resend_owner_invitation', 'Resend owner invitation'), ('cancel_workspace', 'Cancel pending workspace'), ('accept_owner_invitation', 'Accept owner invitation'), ('download_data_export', 'Download installation data export')], max_length=40),
        ),
    ]
