# Generated by Django 6.0.7 on 2026-10-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_data_export_audit_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceaccessevent',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workspaceaccessevent',
            name='action',
            field=models.CharField(choices=[('grant_creator', 'Grant workspace creator'), ('revoke_creator', 'Revoke workspace creator'), ('create_workspace', 'Create workspace'), ('resend_owner_invitation', 'Resend owner invitation'), ('cancel_workspace', 'Cancel pending workspace'), ('accept_owner_invitation', 'Accept owner invitation'), ('download_data_export', 'Download installation data export'), ('invite_member', 'Invite workspace member'), ('accept_member_invitation', 'Accept member invitation'), ('change_member_role', 'Change member role'), ('remove_member', 'Remove workspace member'), ('create_email_connection', 'Create email connection'), ('update_email_connection', 'Update email connection'), ('delete_email_connection', 'Delete email connection'), ('invite_installation_admin', 'Invite installation administrator'), ('accept_installation_admin', 'Accept installation administrator invitation'), ('update_installation_settings', 'Update installation settings')], max_length=40),
        ),
    ]
