# Generated by Django 6.0.7 on 2026-10-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_workspaceaccessevent_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='default_payment_terms_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='document_prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='fiscal_year_start_month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='next_document_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='registration_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='tax_office',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='trading_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='workspaceaccessevent',
            name='action',
            field=models.CharField(choices=[('grant_creator', 'Grant workspace creator'), ('revoke_creator', 'Revoke workspace creator'), ('create_workspace', 'Create workspace'), ('resend_owner_invitation', 'Resend owner invitation'), ('cancel_workspace', 'Cancel pending workspace'), ('accept_owner_invitation', 'Accept owner invitation'), ('download_data_export', 'Download installation data export'), ('invite_member', 'Invite workspace member'), ('accept_member_invitation', 'Accept member invitation'), ('change_member_role', 'Change member role'), ('remove_member', 'Remove workspace member'), ('create_email_connection', 'Create email connection'), ('update_email_connection', 'Update email connection'), ('delete_email_connection', 'Delete email connection'), ('invite_installation_admin', 'Invite installation administrator'), ('accept_installation_admin', 'Accept installation administrator invitation'), ('update_installation_settings', 'Update installation settings'), ('update_workspace_settings', 'Update workspace settings'), ('download_workspace_export', 'Download workspace data export')], max_length=40),
        ),
    ]
