# Generated by Django 6.0.7 on 2026-10-07 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_organizationsettings_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationinvitation',
            name='unique_pending_invitation_per_email',
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspaceaccessevent',
            name='action',
            field=models.CharField(choices=[('grant_creator', 'Grant workspace creator'), ('revoke_creator', 'Revoke workspace creator'), ('create_workspace', 'Create workspace'), ('resend_owner_invitation', 'Resend owner invitation'), ('cancel_workspace', 'Cancel pending workspace'), ('accept_owner_invitation', 'Accept owner invitation'), ('download_data_export', 'Download installation data export'), ('invite_member', 'Invite workspace member'), ('resend_member_invitation', 'Resend member invitation'), ('revoke_member_invitation', 'Revoke member invitation'), ('accept_member_invitation', 'Accept member invitation'), ('change_member_role', 'Change member role'), ('remove_member', 'Remove workspace member'), ('create_email_connection', 'Create email connection'), ('update_email_connection', 'Update email connection'), ('delete_email_connection', 'Delete email connection'), ('invite_installation_admin', 'Invite installation administrator'), ('accept_installation_admin', 'Accept installation administrator invitation'), ('update_installation_settings', 'Update installation settings'), ('update_workspace_settings', 'Update workspace settings'), ('download_workspace_export', 'Download workspace data export')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='organizationinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), fields=('organization', 'email'), name='unique_pending_invitation_per_email'),
        ),
    ]
